# Generated by Django 5.2.7 on 2025-11-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('flight', 'FLIGHT'), ('cab', 'CAB'), ('hotel', 'HOTEL')], max_length=20, verbose_name='Service Type')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('contact', models.PositiveIntegerField(verbose_name='Contact')),
                ('gstin_number', models.CharField(max_length=15, unique=True, verbose_name='GSTN NO.')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('is_restricted', models.BooleanField(default=False, verbose_name='Restricted Provider Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
