# Generated by Django 5.2.7 on 2025-11-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='service_type',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
