# Generated by Django 5.2.7 on 2025-11-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_type',
            field=models.CharField(choices=[('small', 'S'), ('large', 'L'), ('big', 'B')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.CharField(choices=[('IND', 'India'), ('SING', 'Singapore'), ('JPN', 'Japan'), ('ENG', 'ENGLAND')], default='INDIA', max_length=200),
        ),
    ]
