# Generated by Django ...

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_aircraft_aircraft_type_alter_airport_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=100, unique=True)),
            ],
        ),

        migrations.RenameField(
            model_name='terminal',
            old_name='name',
            new_name='terminalname',
        ),

        migrations.AlterModelOptions(
            name='terminal',
            options={'ordering': ['airport', 'terminalname']},
        ),

        migrations.AlterUniqueTogether(
            name='terminal',
            unique_together={('airport', 'terminalname')},
        ),

        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='airport',
                to='flight.airportname'
            ),
        ),
    ]
