# Generated by Django 5.2.7 on 2025-11-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_airportname_alter_terminal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='terminalname',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
