# Generated by Django 5.2.7 on 2025-11-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_alter_terminal_terminalname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='airline',
            field=models.CharField(choices=[('indigo', 'IndiGo'), ('vistara', 'Vistara'), ('airindia', 'Air India'), ('spicejet', 'SpiceJet'), ('akasa', 'Akasa Air')], max_length=20),
        ),
    ]
